name: Conditional Logic Demo

on:
  push:
    branches: [main, feature/*]

jobs:
  conditional-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          echo "Deploying to Production!"
          exit 1   # intentionally fail for demo purposes
        if: github.ref == 'refs/heads/main'

      - name: Run Tests
        run: echo "Running tests on feature branch!"
        if: startsWith(github.ref, 'refs/heads/feature/')

      - name: Notify Failure
        run: echo "🚨 Something went wrong!"
        if: failure()

      - name: Always Cleanup
        run: echo "Cleaning up resources..."
        if: always()

